//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Book", Namespace="http://tempuri.org/XMLSchema.xsd", IsNullable=false)]
public partial class BookType {
    
    private string titleField;
    
    private string authorField;
    
    private string styleField;
    
    private string isbnField;
    
    private string yearField;
    
    private string publisherField;
    
    private string languageField;
    
    private decimal priceField;
    
    private int editionField;
    
    private string genreField;
    
    private string locationField;
    
    private string imageField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public string style {
        get {
            return this.styleField;
        }
        set {
            this.styleField = value;
        }
    }
    
    /// <remarks/>
    public string isbn {
        get {
            return this.isbnField;
        }
        set {
            this.isbnField = value;
        }
    }
    
    /// <remarks/>
    public string year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public string publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
    
    /// <remarks/>
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public int edition {
        get {
            return this.editionField;
        }
        set {
            this.editionField = value;
        }
    }
    
    /// <remarks/>
    public string genre {
        get {
            return this.genreField;
        }
        set {
            this.genreField = value;
        }
    }
    
    /// <remarks/>
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public string image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
}
